# Generated by Django 5.2.8 on 2026-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storeclosureresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoulrestaurantlicense',
            options={'verbose_name': '서울 편의점 인허가 (구별)', 'verbose_name_plural': '서울 편의점 인허가 목록 (구별)'},
        ),
        migrations.AlterModelOptions(
            name='storeclosureresult',
            options={'ordering': ['-checked_at'], 'verbose_name': '폐업 매장 체크 결과 (구별)', 'verbose_name_plural': '폐업 매장 체크 결과 목록 (구별)'},
        ),
        migrations.AlterModelOptions(
            name='tobaccoretaillicense',
            options={'verbose_name': '서울 담배소매업 인허가 (구별)', 'verbose_name_plural': '서울 담배소매업 인허가 목록 (구별)'},
        ),
        migrations.AlterModelOptions(
            name='yeongdeungpoconvenience',
            options={'verbose_name': '서울 편의점 (구별)', 'verbose_name_plural': '서울 편의점 목록 (구별)'},
        ),
        migrations.AlterModelOptions(
            name='yeongdeungpodaiso',
            options={'verbose_name': '서울 다이소 (구별)', 'verbose_name_plural': '서울 다이소 목록 (구별)'},
        ),
        migrations.AddField(
            model_name='seoulrestaurantlicense',
            name='gu',
            field=models.CharField(default='영등포구', max_length=20, verbose_name='구'),
        ),
        migrations.AddField(
            model_name='storeclosureresult',
            name='gu',
            field=models.CharField(default='영등포구', max_length=20, verbose_name='구'),
        ),
        migrations.AddField(
            model_name='tobaccoretaillicense',
            name='gu',
            field=models.CharField(default='영등포구', max_length=20, verbose_name='구'),
        ),
        migrations.AddField(
            model_name='yeongdeungpoconvenience',
            name='gu',
            field=models.CharField(default='영등포구', max_length=20, verbose_name='구'),
        ),
        migrations.AddField(
            model_name='yeongdeungpodaiso',
            name='gu',
            field=models.CharField(default='영등포구', max_length=20, verbose_name='구'),
        ),
    ]
